spring.application.name=backend
server.port=8080

# MongoDB Configuration
# Replace this with your actual MongoDB Atlas URI. We recommend using environment variables in production.
spring.mongodb.uri=mongodb+srv://dk_tm_db_user:dinesh5518@cluster0.pwhmoqx.mongodb.net/taskmanager?appName=Cluster0

# JWT Configuration
taskmanager.app.jwtSecret=${JWT_SECRET:======================TaskManagerPremiumSecretKey===========================}
taskmanager.app.jwtExpirationMs=${JWT_EXPIRATION:86400000}

# Multipart (profile avatars)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Logging
logging.level.org.springframework.security=DEBUG

cloudinary.cloud-name=do9lcquoi
cloudinary.api-key=725763718494168
cloudinary.api-secret=S5WgIxwupdzuiNPAYm236hnERYg