spring.application.name=backend
server.port=8080

# MongoDB Configuration
# Replace this with your actual MongoDB Atlas URI. We recommend using environment variables in production.
spring.data.mongodb.uri=mongodb+srv://dk_tm_db_user:dinesh5518@cluster0.pwhmoqx.mongodb.net/taskmanager?appName=Cluster0

# JWT Configuration
taskmanager.app.jwtSecret=${JWT_SECRET:======================TaskManagerPremiumSecretKey===========================}
taskmanager.app.jwtExpirationMs=${JWT_EXPIRATION:86400000}

# Logging
logging.level.org.springframework.security=DEBUG
